```{r}
getwd()
pf <-read.csv('pseudo_facebook.tsv', sep = '\t')
names(pf)
```

## Histogram of bd

```{r}
library(ggplot2)
qplot(x=dob_day, data=pf) +
  scale_x_continuous(breaks = 1:31) +
  facet_wrap(~dob_month, ncol=3)
  
```
```{r}
qplot(x=friend_count, data=pf, xlim = c(0,1000)) 

# or
qplot(x=friend_count, data=pf, binwidth=25) + 
  scale_x_continuous(limits = c(0,1000), breaks = seq(0,1000, 50)) +
  facet_wrap(~gender, ncol=2)
```

```{r}
qplot(x=friend_count, data=subset(pf, !is.na(gender)), binwidth=25) + 
  scale_x_continuous(limits = c(0,1000), breaks = seq(0,1000, 50)) +
  facet_wrap(~gender, ncol=2)
```
```{r}
table(pf$gender)
by(pf$friend_count, pf$gender, summary)
```

```{r}
qplot(x=tenure/365, data=pf, 
      xlab = 'Number of years using Facebook',
      ylab = 'Number of users in sample',
      binwidth = 0.25, color=I('black'), fill= I('#099DD9')) +
  scale_x_continuous(limits = c(0,7), breaks = seq(1,7,1))
```
```{r}
qplot(x=age, data=pf, 
      xlab = 'Age of users',
      ylab = 'Number of users in sample',
      binwidth = 1, color=I('black'), fill= I('#099DD9')) +
  scale_x_continuous( breaks = seq(0,113,5))


summary(pf$age)
```
```{r}
# Transformations
summary(pf$friend_count)
summary(log10(pf$friend_count + 1))
summary(sqrt(pf$friend_count))



```
```{r}
#Mulptiple plots on one page

install.packages('gridExtra') 
library(gridExtra) 

p1 <- qplot(x = friend_count, data=pf) 

p3 <-  qplot(x = sqrt(friend_count), data=pf)

p2 <-  qplot(x = log10(friend_count),data=pf) 

grid.arrange(p1, p2, p3, ncol=1)

#or ggplot
p1 <- ggplot(aes(x = friend_count), data=pf) + geom_histogram() 

p2 <-  p1 + scale_x_log10() + scale_x_continuous("log10(friend_count)")

p3 <-  p1 + scale_x_sqrt()  + scale_x_continuous("sqrt(friend_count)")

grid.arrange(p1, p2, p3, ncol=1)

```
```{r}
 # Add a scaling level
logScale <-qplot(x = log10(friend_count),data=pf) 
countScale <-ggplot(aes(x = friend_count), data=pf) + geom_histogram() + scale_x_log10()

grid.arrange(logScale, countScale, ncol=2)

qplot(x = friend_count,data=pf) + scale_x_log10()
```

```{r}
#Frequency Polygons
qplot(x=friend_count, y = ..count../sum(..count..), data=subset(pf, !is.na(gender)), binwidth=10 , geom="freqpoly", color=gender) + 
  scale_x_continuous(limits = c(0,1000), breaks = seq(0,1000, 50))+ 
  xlab('Friend Count') + 
  ylab('Percentage of users with that friend count') 

#or ggplot

ggplot(aes(x = friend_count, y = ..count../sum(..count..)), data = subset(pf, !is.na(gender))) + 
  geom_freqpoly(aes(color = gender), binwidth=10) + 
  scale_x_continuous(limits = c(0, 1000), breaks = seq(0, 1000, 50)) + 
  xlab('Friend Count') + 
  ylab('Percentage of users with that friend count')

```
```{r}
qplot(x=www_likes, data=subset(pf, !is.na(gender)),  geom="freqpoly", color=gender) + 
  xlab('Likes') + 
  ylab('Percentage of users with that like count') + 
  scale_x_continuous()+
  scale_x_log10()
```
```{r}
#Summary  
#tapply(pf$www_likes, pf$gender, summary)
tapply(pf$www_likes, pf$gender, sum)
by(pf$www_likes, pf$gender,sum)
```

```{r}
#Box plot (removes data)
qplot(x = gender, y = friend_count, data = subset(pf, !is.na(gender)), geom = 'boxplot', ylim = c(0,1000))


#or (removes data)
qplot(x = gender, y = friend_count, data = subset(pf, !is.na(gender)), geom = 'boxplot') +
  scale_y_continuous(limits = c(0,1000))

#or (limit axes without removing data)

qplot(x = gender, y = friend_count, data = subset(pf, !is.na(gender)), geom = 'boxplot') +
  coord_cartesian(ylim = c(0,250))

by(pf$friend_count, pf$gender, summary)



```
```{r}
#Who initiated more firends?
qplot(x = gender, y = friendships_initiated, data = subset(pf, !is.na(gender)), geom = 'boxplot') +
  coord_cartesian(ylim = c(0,500))

by(pf$friendships_initiated, pf$gender, summary)
```
```{r}
#Getting logical
summary(pf$mobile_likes)
summary(pf$mobile_likes>0)

pf$mobile_check_in <- NA

pf$mobile_check_in <- ifelse(pf$mobile_likes >0, 1, 0)
pf$mobile_check_in <- factor(pf$mobile_check_in)
summary(pf$mobile_check_in)

#percent of mobile check ins
sum(pf$mobile_check_in ==1)/length(pf$mobile_check_in)


```

